# Generated by Django 4.0 on 2022-04-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraccount_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_active',
            new_name='Is_active',
        ),
    ]
